blank_issues_enabled: false
contact_links:
    - name: N64Brew Discord
      url: https://discord.gg/8xvRPqCAFC
      about: Please join for QUESTIONS, conversations or discussions.
    - name: GitHub Discussions
      url:  https://github.com/buu342/N64-UNFLoader/discussions
      about: Alternative channel for asking QUESTIONS.
